### ISSUE TITLE
disable cops in initialization?

### ISSUE THREAD

**Issue by catmando** [reactrb/reactrb-rails-generator#1]
Simply because of the nature of Opal, and Reactrb, I have found these three rubo cops need to be disabled, and suggest we have the option to add these during generation...

``` yml
Style/MutableConstant:
  Enabled: false

Lint/LiteralInCondition:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false
```
